version: 1.0.0-Beta{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore src/SimpleWhiteFixture.sln
build:
  project: src/SimpleWhiteFixture.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
  - cmd: src/packages/xunit.runner.console.2.1.0/tools/xunit.console.exe "c:\Projects\SimpleWhiteFixture\Output\Tests\SimpleWhiteFixture.Example.Tests.dll" /appveyor