version: 1.0.0-Beta{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore src/SimpleWhiteFixture.sln
build:
  project: src/SimpleWhiteFixture.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test:
  assemblies: SimpleWhiteFixture.Example.Tests.dll